version: "3.4"
networks:
  drupal:
    external: true
  proxy:
    external: true
volumes:
  db-data:
    external: true
  db-init-data:
    external: true
  docker-sync-drupal:
    external: true
  docker-sync-drupal-config:
    external: true
secrets:
  AURORA_PASS:
      external: true
  AURORA_USER:
      external: true
  settings.php:
      external: true
  SRCKEY:
      external: true

services:
  php:
    image: testdd
    #image: scbd/drupal-code-base:dev
    # image: wodby/drupal:8-7.1-3.0.0
    # image: scbd/drupal-code-base:dev
    networks:
      - proxy
    volumes:
      - docker-sync-drupal:/var/www/html
      - docker-sync-drupal-config:/var/www/files/config/sync_dir
    environment:
      #ENV: local
      PHP_SITE_NAME: drupal.localhost
      PHP_HOST_NAME: localhost:8000
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
    secrets:
      - SRCKEY
    deploy:
      labels:
        - "traefik.enable=false"
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

  nginx:
    image: wodby/drupal-nginx:8-1.13-3.0.1
    networks:
      - proxy
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - docker-sync-drupal:/var/www/html
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.backend=nginx"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:drupal.localhost"
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

  mailhog:
    image: mailhog/mailhog
    networks:
      - proxy
    deploy:
      labels:
        - 'traefik.backend=mailhog'
        - 'traefik.port=8025'
        - 'traefik.frontend.rule=Host:mailhog.drupal.localhost'
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    ports: #only to connect via tool
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    networks:
      - proxy
    volumes:
#      - db-init-data:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - db-data:/var/lib/mysql # I want to manage volumes manually.
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    deploy:
      labels:
        - "traefik.enable=false"
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
#  webgrind:
#    image: wodby/webgrind:1.5-1.0.0
#    environment:
#      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
#    labels:
#      - 'traefik.backend=webgrind'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:webgrind.drupal.docker.localhost'
#    volumes:
#      - files:/mnt/files
