version: "3.4"

networks:
  drupal:
    external: true
  proxy:
    external: true

volumes:
  db-data:
    external: true
  webgrind-data:
    external: true
  cron-data:
    external: true
  docker-sync-drupal:
    external: true
  docker-sync-drupal-config:
    external: true

secrets:
  AURORA_PASS:
      external: true
  AURORA_USER:
      external: true
  settings.php:
      external: true
  SRCKEY:
      external: true

services:
  php:
    image: scbd/drupal-code-base:dev
    networks:
      - proxy
    volumes:
      - docker-sync-drupal:/var/www/html
      - docker-sync-drupal-config:/var/www/files/config/sync_dir
    environment:
      #ENV: local
      PHP_SITE_NAME: drupal.localhost
      PHP_HOST_NAME: localhost:8000
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
    secrets:
      - SRCKEY
    deploy:
      labels:
        - "traefik.enable=false"
        - "com.centurylinklabs.watchtower.enable=true"
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 240s

  nginx:
    image: wodby/drupal-nginx:8-1.13-3.0.1
    networks:
      - proxy
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - docker-sync-drupal:/var/www/html
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.backend=nginx"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:drupal.localhost"
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

  mailhog:
    image: mailhog/mailhog
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - 'traefik.backend=mailhog'
        - 'traefik.port=8025'
        - 'traefik.frontend.rule=Host:mailhog.drupal.localhost'
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    ports: #only to connect via tool
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    networks:
      - proxy
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    deploy:
      labels:
        - "traefik.enable=false"
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
  watchtower:
    image: v2tec/watchtower
    networks:
      - drupal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup true --label-enable true
    deploy:
      labels:
        - "traefik.enable=false"
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
  cron:
    image: xordiv/docker-alpine-cron:latest
    networks:
      - drupal
    environment:
      CRON_TAIL: true
      CRON_STRINGS: 0 */3 * * * root wget http://drupal.localhost/cron/B5BR_PyII7TBkmBfuh6NTD_PE1m4hyevQBcmUol1koAKdjqpGXmIqyDvO9BUJRBlEBBEpcOYqw
    deploy:
      labels:
        - "traefik.enable=false"
      replicas: 1 # no more then one or boom
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s





  # webgrind:
  #   image: wodby/webgrind:1.5-1.0.0
  #   networks:
  #     - proxy
  #   environment:
  #     WEBGRIND_PROFILER_DIR: /xdebug/profiler
  #   volumes:
  #    - webgrind-data:/xdebug/profiler
  #   deploy:
  #     labels:
  #       - "traefik.enable=true"
  #       - 'traefik.backend=webgrind'
  #       - 'traefik.port=8080'
  #       - "traefik.docker.network=proxy"
  #       - 'traefik.frontend.rule=Host:webgrind.localhost'
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '0.10'
  #         memory: 50M
  #     restart_policy:
  #       condition: any
  #       delay: 10s
  #       max_attempts: 3
  #       window: 120s
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
