site_name: Drupal Docker Stacks <br>(UN Biodiversity)

repo_url: https://github.com/scbd/drupal-docker-stacks
site_description: 'Docker Drupal stacks for local, development, staging and production environments.  Inspired from wodby/docker4drupal'
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Getting Started: 'index.md'
  - Containers:
    - 'Nginx': 'containers/nginx.md'
    - 'PHP': 'containers/php.md'
    - 'MariaDB': 'containers/mariadb.md'
  - Stacks:
    - 'local': 'index.md'
