version: "3.4"
networks:
  portainer:
    external: true
volumes:
  portainer-data:
    external: true
services:
    manage:
      image: portainer/portainer
      networks:
        - portainer
      labels:
        - "traefik.enable=false"
      ports:
        - "9999:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer-data:/data
      deploy:
        replicas: 1
        labels:
          - "traefik.enable=false"
        resources:
          limits:
            memory: 50M
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
          window: 120s
        update_config:
          parallelism: 1
          delay: 15s
