FROM wodby/drupal-php:7.1-3.0.0

ENV DOCROOT_SUBDIR="web" \
    APP_NAME="Drupal 8"

USER root

COPY . ./

RUN set -ex && \
    mv /usr/local/bin/actions.mk /usr/local/bin/drupal-php.mk && \
    chown -R www-data:www-data /var/www/html && \
    su-exec www-data composer install --no-dev  && \
    su-exec www-data composer update  --no-dev && \
    su-exec www-data composer clear-cache  && \
    su-exec www-data mkdir /var/www/files && \
    su-exec www-data mkdir /var/www/files/config && \
    su-exec www-data mkdir /var/www/files/config/sync_dir && \
    su-exec www-data mv -f  /var/www/html/config /var/www/files/config/sync_dir

USER www-data

COPY sh/init /docker-entrypoint-init.d/
COPY sh/actions /usr/local/bin/
